### ISSUE TITLE
[ Issue ] Can't install

### ISSUE THREAD

**Issue by as280093** [Doomsdayrs/shosetsu#1]
Device: Redmi Note 5 Pro
Android version Android Pie

can't install app

**Comment by Doomsdayrs** [comment]
Do you have playstore protect enabled? It might be blocking the install

**Comment by Doomsdayrs** [comment]
It's more likely might be the phone blocks unsigned APKs. Ill get to doing that rn

**Comment by as280093** [comment]
yup protect  google was the issue
