### ISSUE TITLE
[UX] There is no visual cue for chapter list on ln info page

### ISSUE THREAD

**Issue by hXtreme** [Doomsdayrs/shosetsu#10]
The lack of visual cue makes the app harder to learn.

**Comment by Doomsdayrs** [comment]
Elaborate on what you mean by visual cue?

**Comment by hXtreme** [comment]
When I'm on the ln info page there is nothing that tells me that I need to swipe to find the chapter list. So if I didn't know how it was in Tachiyomi, I would have to fiddle around a bit to get it.

**Comment by Doomsdayrs** [comment]
58378a2 address this and fixes it
