### ISSUE TITLE
[BUG] Parsing leaves a div tag

### ISSUE THREAD

**Issue by hXtreme** [Doomsdayrs/shosetsu#11]
Chapters of Release that Witch from Box Novel is surrounded by div tag.

The same also happens with every other ln I've tried from Box Novel.

![Screenshot_2019-07-11-04-30-25-143_com github doomsdayrs apps shosetsu](https://user-images.githubusercontent.com/22425371/61035415-19cf9580-a395-11e9-9be0-5483eecbc80b.png)

**Comment by Doomsdayrs** [comment]
This is an issue related to novelreader-extensions, but will be addressed

**Comment by Doomsdayrs** [comment]
77f1a02 Fixes this with an updated extensions library
