### ISSUE TITLE
[Feature Request] Navigation sidebar clickable email link

### ISSUE THREAD

**Issue by hXtreme** [Doomsdayrs/shosetsu#13]
![Screenshot_2019-07-11-04-49-42-723_com github doomsdayrs apps shosetsu](https://user-images.githubusercontent.com/22425371/61036692-94011980-a397-11e9-9c00-c5b0fce057c3.png)

Make it so that clicking on the email opens a mailto link.

Alternatively swap out the email for GitHub repo link.

**Comment by Doomsdayrs** [comment]
4c75a00 Addresses this, now uses github repo link and when clicked opens browser to said link
