### ISSUE TITLE
[UI] Vertically middle align source name

### ISSUE THREAD

**Issue by hXtreme** [Doomsdayrs/shosetsu#17]
Currently source name is vertically aligned to top.

![Screenshot_2019-07-13-13-04-22-149_com github doomsdayrs apps shosetsu](https://user-images.githubusercontent.com/22425371/61174490-daf53780-a56e-11e9-91b2-452ed5c24f7c.png)

You may also want to add some left padding to the text so that it's not sticking to the image.

**Comment by Doomsdayrs** [comment]
e221547 Padded
