### ISSUE TITLE
[UI] Extra space above cover image

### ISSUE THREAD

**Issue by hXtreme** [Doomsdayrs/shosetsu#22]
![Image](https://user-images.githubusercontent.com/22425371/61230798-c5137e00-a6f8-11e9-9ad1-563fad95d5a1.png)

**Comment by Doomsdayrs** [comment]
#21 and this one are both issues with the novel card, i currently am working on figuring out why it causes me such a headache in design.

**Comment by Doomsdayrs** [comment]
I don't seem to get why the f there is a border on the top

**Comment by hXtreme** [comment]
Try removing the rounded corners see if that fixes it.

**Comment by Doomsdayrs** [comment]
Did so, there is still a border

**Comment by Doomsdayrs** [comment]
Have you got an idea?

**Comment by hXtreme** [comment]
It just seems like I'd need to go through all the constraints and manually set them up in the layout.

**Comment by Doomsdayrs** [comment]
manually?

**Comment by hXtreme** [comment]
Using the text view instead of design view in android studio.
