### ISSUE TITLE
[Bug] Chapters dont resume

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#32]
Trying to read books and I noticed that it says POSITION so I assume it keeps track where you left off in a chapter.

It doesn't seem to resume for me. Position number is 42962 with a short chapter. Not sure how I bugged out here. 

Also. Adding a button for easy resuming VS finding the chapter I left off on. I'm starting a 1000+ chapter series and scrolling down to find my chapter would be a bit cumbersome. 

Using takiyomi as a reference they have a play button to continue reading. 
![Screenshot_20190803-134309_Tachiyomi](https://user-images.githubusercontent.com/53633953/62415253-b67ffe80-b5f4-11e9-8530-bcb3440c14ef.jpg)

![Screenshot_20190803-133517_Shosetsu](https://user-images.githubusercontent.com/53633953/62415234-63a64700-b5f4-11e9-8042-54010abf6946.jpg)

**Comment by Doomsdayrs** [comment]
Funnily enough, i just saw this issue JUST as i realized the program was missing a scroll setter XD
