### ISSUE TITLE
[Suggestion] "Continue reading" button

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#33]
Picking up where you left off can be a chore with longer novels that have hundreds of chapters.

A resume reading option would be nice!

Takiyomi for reference 

![Screenshot_20190803-134309_Tachiyomi](https://user-images.githubusercontent.com/53633953/62415286-4faf1500-b5f5-11e9-94af-215f3dc9f74f.jpg)

**Comment by BanditKingJing** [comment]
Maybe also change the color of read, reading and unread too?

**Comment by Doomsdayrs** [comment]
Separate that to another issue
