### ISSUE TITLE
[Suggestion] add color shades (gray) to read/reading chapters

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#34]
![Screenshot_20190803-191356_Shosetsu](https://user-images.githubusercontent.com/53633953/62418120-23fd5080-b630-11e9-9313-95ade7c6c167.jpg)
Title. 

Easier to find what you read.

**Comment by Doomsdayrs** [comment]
Alright time to learn how to shade tomorrow
