### ISSUE TITLE
[Bug] Chapters not showing as READ

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#35]
![Screenshot_20190804-010702_Shosetsu](https://user-images.githubusercontent.com/53633953/62419686-4608ca00-b654-11e9-8d37-d20e9d9c4d1b.jpg)

Title. 

When I'm done reading a chapter I back out to start the next one and it always shows a high position and "reading"

It's fixed by going back in and scrolling to the very bottom and backing out again.

**Comment by Doomsdayrs** [comment]
This issue has been resolved in the current DEV enviroment

**Comment by BanditKingJing** [comment]
Issue still persists
