### ISSUE TITLE
[Bug] flipping orientation back and forth messes up paragraph spacing

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#37]
Title

![ZomboDroid 06082019123233](https://user-images.githubusercontent.com/53633953/62558129-6a2bfd00-b846-11e9-9280-bf15ecee1f13.jpg)

So I'm laying down reading and the orientation flips horizontal. When rotated back to vertical the paragraph spacing is way off.

**Comment by Doomsdayrs** [comment]
This is an interesting issue, I'll check the dev build to see if it is fixed

**Comment by Doomsdayrs** [comment]
Fixed in dev
