### ISSUE TITLE
[Bug] chapters still don't show as READ

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#42]
![Screenshot_20190809-085901_Shosetsu](https://user-images.githubusercontent.com/53633953/62780565-ff680500-ba83-11e9-8da8-3993dd73f086.jpg)
Happens maybe 9/10 times. Often doesn't trigger as read.

**Comment by hXtreme** [comment]
Idea: maybe we can use the scroll position to determine if the chapter was read.

We can set some threshold say, 95%. If the scroll position is at 95% or above of the total 'length' then we consider it as read.

**Comment by BanditKingJing** [comment]
Issue still persists

**Comment by Doomsdayrs** [comment]
I'll try the 95% idea

**Comment by BanditKingJing** [comment]
Down to test as soon as we got a build with it. I don't have time to compile a apk myself
