### ISSUE TITLE
[Suggestion/bug?] "next chapter" button covers text

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#43]
![Screenshot_20190809-090012_Shosetsu](https://user-images.githubusercontent.com/53633953/62780664-33dbc100-ba84-11e9-9c10-ba0e69e20b68.jpg)
Add a space at the end of a book so the button doesn't cover the last sentence? Hard to read under it.

**Comment by hXtreme** [comment]
Dirty fix: Append a few newlines to the chapter text.

**Comment by Doomsdayrs** [comment]
Better fix, move scroll view up.
