### ISSUE TITLE
[Bug] Search catalog thumbnails are zoomed in

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#46]
Basically title.

![ZomboDroid 07092019111122](https://user-images.githubusercontent.com/53633953/64476712-9649df00-d160-11e9-8939-c6a37d8a1df0.jpg)

Small things to polish it up.

**Comment by Doomsdayrs** [comment]
This seems to be an issue with novelfull only, and has been for stupid long xD
