### ISSUE TITLE
F-Droid Support

### ISSUE THREAD

**Issue by roshavagarga** [Doomsdayrs/shosetsu#50]
Hello,

Have you considered applying to have Shosetsu added to F-Droid?

**Comment by BanditKingJing** [comment]
you can add it manually but idk github well enough to get a distro link. Just too lazy to look into it. I pay attention to discord pings.

**Comment by Doomsdayrs** [comment]
ITs soooooo complicated

**Comment by roshavagarga** [comment]
You can start the process and let it stew on gitlab. Some apps get submitted by the owners with an admission that they do not have the time to fix everything but are open to help and volunteers help them out :)

**Comment by roshavagarga** [comment]
You can also just give approval and I can at least fill it out so that your app gets checked?

**Comment by roshavagarga** [comment]
@Doomsdayrs Are you at least open to having Shosetsu added to F-Droid?

**Comment by Doomsdayrs** [comment]
Yes i am, i just don't have the patience to try and figure out how to do it xD

**Comment by roshavagarga** [comment]
@Doomsdayrs
1. It has to conform to the [these](https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy).
2. If 1 is true, then open a merge request [here](https://gitlab.com/fdroid/fdroiddata/merge_requests).

Then it just has to be checked for building, if everything's alright, it gets added by the F-Droid volunteers when everything has been a-okay'd.

**Comment by Doomsdayrs** [comment]
TBH why can't there be an automated way to do this, seems so complicated for a simple appstore

**Comment by roshavagarga** [comment]
Because F-Droid is centered around submitted apps being FLOSS. Nothing used to maintain, create or enable the app's functionality can be non-free. While some of this can and is automated, other parts are viewed by humans to make sure no shenanigans happen.

**Comment by BanditKingJing** [comment]
A workaround could be to setup a repo and simply manually add it as a source in fdroid?

https://help.github.com/en/articles/about-remote-repositories

**Comment by BanditKingJing** [comment]
Takiyomi repo for example

https://j2ghz.github.io/repo

**Comment by Doomsdayrs** [comment]
So if we just have a file in this repo that is just like that repo, then we can add it to fdroid?

**Comment by Doomsdayrs** [comment]
ah, nvm i get it now

**Comment by roshavagarga** [comment]
I'd still recommend going through the motions and getting it added to the F-Droid repo. There is currently no app for reading light novels and/or web novels on F-Droid. LNReader is under review and might be added at some point.

**Comment by IzzySoft** [comment]
@Doomsdayrs not that hard. Someone just [opened a Request For Packaging](https://gitlab.com/fdroid/rfp/issues/1189). But may I suggest you add [Fastlane file structure](https://gitlab.com/snippets/1895688) to your repo here – to provide screenshots and manage the app description yourself? Fastlane can also be used for deployment to Google Play btw.

For the screenshots in Fastlane I suggest using "non-framed" ones – considering the small screen estate on phones. That way the users get more details :wink:

For the description:

* where does Shosetsu obtain its novels from? Looks like it uses some web scraper. Can sources (book sites) be freely configured, or is there a "fixed set"? Can book servers even be self-hosted, maybe?
* What book formats are supported? The libraries give no clue (except for Markdown maybe), and from `ui/reader/viewHolders/` I could guess also plain-text.

For a pre-check, I've just added your app to my repo (should turn up [here](https://apt.izzysoft.de/fdroid/index/apk/com.github.doomsdayrs.apps.shosetsu) with tomorrow's sync – today's sync just was done an hour ago) – it seems to meet the criteria for the official repo.

Oh, almost forgot to disclose: I'm one of the F-Droid maintainers.

**Comment by Doomsdayrs** [comment]
Seems like an easy thing to do, I'll be able to get it done tonight

**Comment by IzzySoft** [comment]
Great, thanks! Just ping me again when it's ready. That bot of ours will also be run until then (hopefully; runs once per day and I never remember at what time :rofl:)

**Comment by Doomsdayrs** [comment]
@IzzySoft 9829de0 on master adds fastlane support, tho i don't have a featureGraphic, tvBanner, or promoGraphic

**Comment by IzzySoft** [comment]
@Doomsdayrs that's fully fine – all elements are optional. Now we just need a tag covering fastlane, and we can go on. The bot has scanned your repo meanwhile; it spit two warnings you might wish to look at (not affecting builds done by F-Droid, but your own).

**Comment by Doomsdayrs** [comment]
Hmm, Ill added the keys

**Comment by Doomsdayrs** [comment]
@IzzySoft Seems android studio doesn't support building with the sum's, Oh well

**Comment by IzzySoft** [comment]
I vaguely remember there were some issues introduced by a Studio update – but not being an Android dev myself, I don't remember the solution. Well, feel free to ignore that warning then: as I wrote, it's no show-stopper for F-Droid as we replace this part anyway. Just have a tag covering fastlane, and I can mark the RFP for our packagers to process.

**Comment by roshavagarga** [comment]
@IzzySoft New tag released, did that have to cover an update to the version code too or is it good as is?

**Comment by Doomsdayrs** [comment]
@IzzySoft v1.1.1 (code 24) released just now, isn't different to v1.1.0, just a code upgrade and scheme increment

**Comment by IzzySoft** [comment]
Thanks! I've just [prepared the metadata](https://gitlab.com/fdroid/rfp/issues/1189#note_267222241) in the RFP and marked it ready for packaging.

Concerning your previous edit: yes, a new tag/release should always have `versionCode` increased – that's what Android tells versions apart and decides which one is the newer. As this is the first version we're packaging at F-Droid, it doesn't much matter *for us* this time – but for the future, please remember it :wink:

Now we're waiting for a packager to pick up. As the F-Droid team is permanently understaffed, it might take a little. Should nothing happen in, say, about 2 weeks, feel free to ping me again so I can check (and forward the ping to our packagers).

**Comment by Doomsdayrs** [comment]
@IzzySoft A ping for you!

**Comment by IzzySoft** [comment]
@Doomsdayrs forwarded, thanks!

**Comment by Doomsdayrs** [comment]
Added to fdroid as of https://gitlab.com/fdroid/fdroiddata/merge_requests/6212

**Comment by IzzySoft** [comment]
Congrats! I'll then [remove it from my repo](https://apt.izzysoft.de/fdroid/index/info#delete) as soon as it pops up at f-droid.org (you've stopped attaching APKs after v1.1.0 anyway, so I'm no longer able to update; you might wish to fill that gap for v1.1.3 to bridge the time until then).

**Comment by Doomsdayrs** [comment]
I stopped attaching apks because all the versions are the same code wise ;p

**Comment by IzzySoft** [comment]
Ah, I should have read the release notes :rofl:
