### ISSUE TITLE
[Bug] dark mode is broken

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#52]
Title. Background doesn't change
![Screenshot_20191221-141959_Shosetsu-Development](https://user-images.githubusercontent.com/53633953/71312868-69af8f80-23fe-11ea-808b-41b00730380f.jpg)

**Comment by BanditKingJing** [comment]
Update.

Workaround. Dark mode works fine once you're reading. 
Menu>Night mode.
Seems like SETTINGS is broken

**Comment by Doomsdayrs** [comment]
5b91f32 Fixes Advanced setting refresh
0f58ab3 Clarifies that ViewSettings night mode is for reader
