### ISSUE TITLE
[Bug] chapters don't load

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#53]
Process
Open novelfull 
Search title
Overgeared and "I alone level up" tested
Refresh to load into. 
Description loads
Chapter list does NOT. Although it looks like it downloads. 

![ZomboDroid 21122019143308](https://user-images.githubusercontent.com/53633953/71312893-e478aa80-23fe-11ea-98df-0dbb9f7fda27.jpg)

**Comment by BanditKingJing** [comment]
Reloaded the app and tried too many things to count.
Both examples loaded in library and only 50 chapters load out of over 1000

**Comment by BanditKingJing** [comment]
![Screenshot_20191221-151754_Shosetsu-Development](https://user-images.githubusercontent.com/53633953/71313320-1db41900-2405-11ea-87c6-8b427122c6da.jpg)

**Comment by Doomsdayrs** [comment]
Fix one thing, another 200 breaks 
I'm guessing this is an issue on the super old and dirty method of loading chapters and more i coded

**Comment by BanditKingJing** [comment]
Big issue cause I can't read with it! Haha.

**Comment by Doomsdayrs** [comment]
After MANY hours of code today. I am safe to say SHIT this is crap i need to redo everything

**Comment by BanditKingJing** [comment]
Well at least you're making progress!
Godpseed

**Comment by Doomsdayrs** [comment]
Fixed with latest dev a15b771
