### ISSUE TITLE
[Bug] [v1.0.0-dev-rc2] crash on download screen

### ISSUE THREAD

**Issue by BanditKingJing** [Doomsdayrs/shosetsu#54]
Not sure how to replicate.

Queue 200 chapters to download on one LN. 

Refresh another LN while downloading. 

Hangs. Doesn't load second LN. 

Check download screen crashes. 

Reopen app. crashes on downloads screen again.

Redownload 1st LN. Wait till done. 

Downloads opens fine empty.

**Comment by Doomsdayrs** [comment]
Figured it out, This is likely due to an issue with how the application currently handles workloads. 


Currently it delegates all async with AsyncTask, But this is a critical flaw. 
https://developer.android.com/guide/background using this guide, I a thread improvement is on schedule

**Comment by hXtreme** [comment]
Removing UX label as this looks more of a performance issue.(maybe something to do with multi threading or lack thereof)

**Comment by Doomsdayrs** [comment]
WorkerManager/ DownloadManager for Downloads
AlarmManager for Updating (possibly WorkerManager aswell)
Foreground services for UI tasks

**Comment by Doomsdayrs** [comment]
Solved issue
