### ISSUE TITLE
[UI] New ICON for app

### ISSUE THREAD

**Issue by hXtreme** [Doomsdayrs/shosetsu#6]
In recent years interface design paradigm has been moving towards flat icons and interface and to better align with this consider removing shadows and borders from the following:

![Screenshot_2019-07-11-00-44-28-662_com github doomsdayrs apps shosetsu](https://user-images.githubusercontent.com/22425371/61022779-4d022c80-a375-11e9-982d-691ae297b32b.png)
![Screenshot_2019-07-11-00-45-08-157_com github doomsdayrs apps shosetsu](https://user-images.githubusercontent.com/22425371/61022794-58555800-a375-11e9-9a47-6da886c6a068.png)

At the same time also consider smaller font size for ln title in catalogue.

Consider checking out [Material design guidelines](https://material.io/design/).

**Comment by Doomsdayrs** [comment]
Borders have been fixed. New ICON to be decided

**Comment by Doomsdayrs** [comment]
Finished, v1.0.0 fixes
