### ISSUE TITLE
[UX] Easily distinguishable icon for "Add to Library"

### ISSUE THREAD

**Issue by hXtreme** [Doomsdayrs/shosetsu#9]
The icon for Add to Library and the icon after adding look confusingly similar.

![Screenshot_2019-07-11-04-15-54-111_com github doomsdayrs apps shosetsu](https://user-images.githubusercontent.com/22425371/61034293-fc99c780-a392-11e9-954b-32e3536a563f.png)

![Screenshot_2019-07-11-04-15-59-375_com github doomsdayrs apps shosetsu](https://user-images.githubusercontent.com/22425371/61034306-015e7b80-a393-11e9-8577-51d1a2a7f8cc.png)

**Comment by Doomsdayrs** [comment]
I'm not sure on how to improve on this, would a larger image in the floating action help? or a change of its background color?

**Comment by hXtreme** [comment]
You can have two different icons. Tachiyomi does a good job with it so check it out, maybe that can give some inspiration.

**Comment by hXtreme** [comment]
Checkmark was suggested in #65

**Comment by Doomsdayrs** [comment]
![Screenshot_1578169771](https://user-images.githubusercontent.com/38189170/71771321-06962080-2f07-11ea-8287-520921df00b0.png)
ae0f8b6 adds checkmark, how does it look

**Comment by BanditKingJing** [comment]
Definitely distinguishable now! Thanks

**Comment by hXtreme** [comment]
Could we possibly have the icons be bigger to fill more space inside the button?

**Comment by Doomsdayrs** [comment]
![Screenshot_1578172686](https://user-images.githubusercontent.com/38189170/71771704-cdad7a00-2f0d-11ea-891c-037a0da7bc4e.png)
32dp size, How is it?

**Comment by hXtreme** [comment]
Looks good, just make sure you're also changing the size for the initial icon.

**Comment by Doomsdayrs** [comment]
Its vector, I just increased the icon size in FAB

**Comment by hXtreme** [comment]
Closed by: ae0f8b6

**Comment by BanditKingJing** [comment]
Simple and effective solution!
